#!/usr/bin/env bash

socialos_resolve_profile() {
  local requested="${1:-demo}"
  case "${requested}" in
    demo)
      printf 'demo\n'
      ;;
    local|blank|personal)
      printf 'local\n'
      ;;
    *)
      echo "Unknown SocialOS profile: ${requested}" >&2
      return 1
      ;;
  esac
}

socialos_default_db_path() {
  local repo_root="$1"
  local profile
  profile="$(socialos_resolve_profile "${2:-demo}")"
  case "${profile}" in
    demo)
      printf '%s\n' "${repo_root}/infra/db/socialos.demo.db"
      ;;
    local)
      printf '%s\n' "${repo_root}/infra/db/socialos.local.db"
      ;;
  esac
}

socialos_write_env_local() {
  local target_path="$1"
  local profile
  profile="$(socialos_resolve_profile "${2:-demo}")"
  local db_path="$3"

  mkdir -p "$(dirname "${target_path}")"
  cat >"${target_path}" <<EOF
# Auto-generated by SocialOS bootstrap scripts.
SOCIALOS_PROFILE=${profile}
SOCIALOS_DB_PATH=${db_path}
EOF
}
